### ISSUE TITLE
Can't get date to parse

### ISSUE THREAD

**Issue by dstroot** [empatica/csvparser#6]
My csv records look like this:

`EFE43362N14JDUC9,10/21/2015 0:00`

I can't seem to get this date to parse.  struct below:

```
type DetailRecord struct {
	ID          string
	Date        time.Time `csvDate:"10/21/2015 0:00"`
}
```

any help would be appreciated.

**Comment by alecha** [comment]
Hi, did you solve the issue? actually the `csvDate` is wrong, because you should put the format of the default date specified in the go documentation

**Comment by dstroot** [comment]
That was exactly the problem!

Best Regards,
Dan
