### ISSUE TITLE
Read Csv to a []Struct

### ISSUE THREAD

**Issue by andre-mota** [empatica/csvparser#7]
Hi,

Sorry if it's a dumb question, but i'm starting with Go and I'm having some difficulties with this.
How can I make something like

    var myVar []MyStruct
    var myVar2 MyStruct

Then i need to read each line for the myVar2 and parse it to myVar, so in the end I have a []MyStruct that i can use?

Thanks,
Great work!

**Comment by alecha** [comment]
In the README there is a simple example on how to do it:

```go
var myVar,_ = csvParser.Parse(MyStruct{})

for i := 0; i < len(myVar); i++ {
  myVar2 := myVar[i].(* MyStruct)
}
```

**Comment by andre-mota** [comment]
Thanks! :)
