### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by andre-mota** [empatica/csvparser#8]
Hi, 

I can't seem to find a date format that works with the date in my CSV.

What I have is this:

    2015-12-23 00:00:00+0000

Any idea of what is the correct date format?

Thanks!

**Comment by alecha** [comment]
hi! you can read more about the right format [here](https://golang.org/pkg/time/#Parse).

I assume that the right format in your case is the following one:

`2006-01-02 15:04:05-0700`

**Comment by andre-mota** [comment]
Thanks! :)
